config/routes.rb
Rails.application.routes.draw do

  root :to=>'access#new'
  resources :users
  resources :categories
  resources :items
  resources :access,only: [ :new, :create, :destroy ]
  resources :setup_organization,only: [ :show,:update ]
  resources :admin,only: [:index]

  resources :cart,except: [:new,:show] do
    collection do
      get :clean
    end
  end


  resources :menus  do
    member do
      get :list
    end
  end

  resources :restaurants do
    member do
      get :menage
    end
  end

  resources :daily_menus do
    member do
      get :menage
      put :toggle_visibility
    end
  end

  get 'registration',:to=>'users#new'
  get 'home', :to => 'home#index'

end

app/models/Tenant.rb
class Tenant

  def initialize(user)
    @user = user
  end

  def restaurants
    owner? ?  Restaurant.where('organization_id = ?',@user.organizations.first.id).all : Restaurant.all.all
  end

  private



  def admin?
    @user.has_role? "admin"
  end

  def owner?
    @user.has_role? "owner" if @user
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new #not logged in user
      if user.has_role? :admin
        can :manage, :all
      elsif user.has_role? :owner
        can :manage,Restaurant,:organization_id => user.organizations.first.id
        can :manage,Menu
        can :manage,:admin
        can :read, :home

      else
        can :read, :home
      end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :items
   has_many :menus
  validates :name,
            :presence => true
end

app/models/daily_menu.rb
class DailyMenu < ActiveRecord::Base

  has_many :items,dependent: :destroy
  belongs_to :restaurant,:dependent => :destroy

  accepts_nested_attributes_for :items,
                                :allow_destroy => true,
                                :reject_if => :all_blank

  validates :title,
            :presence => true

  validates :restaurant_id,
            :presence=> true

  validates :price,
            :presence => true,
            :numericality => true
end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :menu
  belongs_to :daily_menu
  belongs_to :category

  validates :name,
            :presence => true
           # :length => {minimum: 2,maximum: 45}
 # validates :price,
           # :presence => true,
           # :numericality => true
  validates :category_id,
            :presence => true

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :restaurant
  has_many :categories,:through => :items
  has_many :items,:dependent => :destroy

  validates :title,
            :presence => true


end

app/models/organization.rb
class Organization < ActiveRecord::Base
  resourcify #rolify

  has_and_belongs_to_many :users
  has_many :restaurants

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_one :menu,dependent: :destroy
  has_many :daily_menus,dependent: :destroy

  belongs_to :organization
  validates :name,
            presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify #rolify gem
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  has_secure_password
  has_one :plan
  has_many :restaurants,:through => :organizations

  has_and_belongs_to_many :organizations

  validates :username,
            :presence => true,
            :uniqueness => true,
            :length => { maximum: 30 }

  validates :email,
            presence: true,
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }



end

app/controllers/daily_menus_controller.rb
class DailyMenusController < ApplicationController
  layout 'admin_menage_restaurant',:exept => :show

  def index
    @daily_menu= DailyMenu.all
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id]) || Restaurant.find(params[:daily_menu][:restaurant_id])
    @daily_menu = DailyMenu.new
    1.times{@daily_menu.items.build}
  end

  def create
    @daily_menu = DailyMenu.new(daily_menu_params)
    if @daily_menu.save
      redirect_to menage_restaurant_path(@daily_menu.restaurant_id)
    else
      render 'daily_menus/new'
    end
  end

  def edit
    @daily_menu = DailyMenu.find(params[:id])
    @restaurant = Restaurant.where(:id => @daily_menu.restaurant_id)
  end

  def update
    @daily_menu = DailyMenu.find(params[:id])
    respond_to do |format|
      if @daily_menu.update(daily_menu_params)
        format.html{redirect_to menage_daily_menu_path(@daily_menu.restaurant_id),notice: 'Created'}
        format.js{}
      end
    end
  end

  def destroy
    @daily_menu = DailyMenu.find(params[:id])
    respond_to do |format|
      if @daily_menu.delete
        @daily_menu.items.delete_all
        format.html{redirect_to menage_restaurant_path(@daily_menu),notice:"Successfully deleted" }
        format.js{}
      else
        flash[:notice]="neide "
      end
    end
  end

  def menage
    @daily_menu = DailyMenu.where(:restaurant_id => params[:id])
    @restaurant = Restaurant.find(params[:id])

  end

  def toggle_visibility
    @daily_menu = DailyMenu.find(params[:id])
    @daily_menu.toggle!(:visibility)
  end


  private

  def daily_menu_params
    params.require(:daily_menu).permit(:title,:restaurant_id,:price,:visibility,items_attributes:[:id,:name,:category_id,:description,:menu_type,:daily_menu_id,:_destroy])
  end




end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for(object)
    #render error message(views/application html template),i prilagodjavanje lokalnih varijabli unutar 'application/error_message sa ulaznom
    render(:partial => 'application/error_messages', :locals => {:object => object})
  end

  def plan_name(plan_id)
    plan_name = Plan.where(:id => plan_id).pluck(:name).first
  end

  def active_link?(test_path)
    return 'active' if request.original_url == test_path
    ''
  end

  def set_visibility_text(obj)
    if obj.visibility
      "Visible"
    else
      "Hiden"
    end
  end

  def set_class_for_visibility(obj)
    if obj.visibility
      "btn btn-danger btn-md visibility"
    else
      "btn btn-primary btn-md visibility"
    end
  end



end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/daily_menus_helper.rb
module DailyMenusHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/daily_menus/_daily_menu.html.erb
    <div class="col-lg-4 col-md-3 col-xs-6 daily_menu">
      <ul class="plan plan1">
        <li class="plan-name">
          <%= daily_menu.title.capitalize%>
        </li>
        <% daily_menu.items.each do |item|%>
        <li>
         <strong>Name: <%= item.name.capitalize %></strong><br>
          <small><strong> <%= item.description.capitalize %></strong></small>
        </li>
        <% end %>
        <li class="plan-price">
          <strong>Price: <%= daily_menu.price %> / €</strong>
        </li>
        <li class="plan-action">
          <%= link_to "Edit",edit_daily_menu_path(daily_menu.id),:class => "btn btn-success  btn-md edit_daily",remote: true %>
          <%= link_to set_visibility_text(daily_menu),toggle_visibility_daily_menu_path(daily_menu.id),:data=>{loading_text:'Loading'},:class => set_class_for_visibility(daily_menu),remote: true,method: :put%>
          <%= link_to "Delete",daily_menu_path(daily_menu.id),:class => "btn btn-warning  btn-md delete_daily",:method => :delete,remote: true  %>
        </li>
      </ul>
    </div>

app/views/daily_menus/_form.html.erb
  <%= error_messages_for(@daily_menu)%>

  <%= form_for @daily_menu  do |f| %>

    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, :class=>"form-control", :placeholder => "Daily Menu Name" %>
      <%= f.hidden_field :restaurant_id ,:value => params[:restaurant_id] || @daily_menu.restaurant_id %>
    </div>

    <div class="form-group ">
      <%= f.label :price %><br>
      <%= f.text_field :price, :class=>"form-control", :placeholder => "Daily Menu Price"%>

    </div>

    <h2>Meals</h2>

    <%= render :partial=>"daily_menus/items",:locals=>{f:f} %>

    <div id="itemsWrapper"></div>

     <div class="form-group">
        <%= f.submit "Create Daily Menu",:class=>"btn btn-primary "%>
        <%= link_to "Add New Meal",'#',:class=>"btn btn-success newItem"%>
  <% end %>
     </div>

app/views/daily_menus/_items.html.erb
<%= f.fields_for :items  do |i|%>
    <div class="form-group col-lg-12">
      <div class="col-lg-4">
        <%= i.label :name,:class=>'label_name' %><br>
        <%= i.text_field :name,:class=>"form-control", :placeholder => "Price for Daily Menu"%>
      </div>

      <div class="col-lg-4">
        <%= i.label :category %><br>
        <%=i.select(:category_id,options_from_collection_for_select(Category.all,:id,:name),{ :prompt=>"Izaberite kategoriju jela" },{:class=>"form-control"}) %>
      </div>

      <div class="col-lg-4">
        <%= i.label :description %><br>
        <%= i.text_field :description,:class=>"form-control", :placeholder => "Short Description"%>
        <%= i.hidden_field :menu_type, :value =>false %>
      </div>
    </div>
<%end%>

app/views/daily_menus/destroy.js.erb
$('.delete_daily').on('ajax:success',function(){
    $(this).closest('.daily_menu').fadeIn(1000,function(){
        $(this).remove();
    });
});

app/views/daily_menus/edit.js.erb
    var modal = $('.add_new_modal');
    var title = $('.modal-title');

    title.empty();
    modal.find('.modal-body').empty();

    title.append('Edit ').addClass('text-center');
    modal.find('.modal-body').append("<%= j render :partial =>'daily_menus/form'%>");
    modal.modal();



$('.newItem').on('click',function(){
    var x = $('.label_name').length - 1;
        /* function for appending nested item in daily menu( app/javascript/daily_menu.js)*/
    append_nested_form_to_daily_menu_form(x)
});
$("#itemsWrapper").on("click",".remove_field", function(e){
        event.preventDefault();
        $(this).parent('div').remove();
        x--;

});

app/views/daily_menus/index.html.erb
<h3>Daily Menus</h3>

<% @daily_menu.each do |menu| %>
    <%= menu.title  %>
<% end %>

app/views/daily_menus/menage.html.erb
<div class="row">
  <% if !@daily_menu.empty? %>
    <%= render @daily_menu  %>
   <% else %>
    <h3>No Daily Menus</h3>
   <% end %>
</div>

app/views/daily_menus/new.html.erb
 <%= render :partial => 'daily_menus/form' %>

app/views/daily_menus/toggle_visibility.js.erb
//$('.visibility').on('beforeSend',function(){
$.ajax({
success: function(){


},
 beforeSend:function(obj){
     var obj = $(this)
     var text = obj.prop('text')
     alert(text)
     obj.button('loading');
     setTimeout(function () {
         obj.button('reset')
         if( text == 'Visible'){
             obj.text('Hiden');
             obj.removeClass('btn btn-danger').addClass('btn btn-default')
         } else {
             obj.text('Visible');
             obj.removeClass('btn btn-default').addClass('btn btn-danger')
         }

     },1000)
}
})