config/routes.rb
Rails.application.routes.draw do

  root :to=>'access#new'
  resources :users
  resources :categories
  resources :items
  resources :access,only: [ :new, :create, :destroy ]
  resources :setup_organization,only: [ :show,:update ]
  resources :admin,only: [:index]

  resources :cart,except: [:new,:show] do
    collection do
      get :clean
    end
  end


  resources :menus  do
    member do
      get :list
    end
  end

  resources :restaurants do
    member do
      get :menage
    end
  end

  resources :daily_menus do
    member do
      get :menage
      put :toggle_visibility
    end
  end

  get 'registration',:to=>'users#new'
  get 'home', :to => 'home#index'

end

app/models/Tenant.rb
class Tenant

  def initialize(user)
    @user = user
  end

  def restaurants
    owner? ?  Restaurant.where('organization_id = ?',@user.organizations.first.id).all : Restaurant.all.all
  end

  private



  def admin?
    @user.has_role? "admin"
  end

  def owner?
    @user.has_role? "owner" if @user
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new #not logged in user
      if user.has_role? :admin
        can :manage, :all
      elsif user.has_role? :owner
        can :manage,Restaurant,:organization_id => user.organizations.first.id
        can :manage,Menu
        can :manage,:admin
        can :read, :home

      else
        can :read, :home
      end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :items
   has_many :menus
  validates :name,
            :presence => true
end

app/models/daily_menu.rb
class DailyMenu < ActiveRecord::Base

  has_many :items,dependent: :destroy
  belongs_to :restaurant,:dependent => :destroy

  accepts_nested_attributes_for :items,
                                :allow_destroy => true,
                                :reject_if => :all_blank

  validates :title,
            :presence => true

  validates :restaurant_id,
            :presence=> true

  validates :price,
            :presence => true,
            :numericality => true
end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :menu
  belongs_to :daily_menu
  belongs_to :category

  validates :name,
            :presence => true
           # :length => {minimum: 2,maximum: 45}
 # validates :price,
           # :presence => true,
           # :numericality => true
  validates :category_id,
            :presence => true

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :restaurant
  has_many :categories,:through => :items
  has_many :items,:dependent => :destroy

  validates :title,
            :presence => true


end

app/models/organization.rb
class Organization < ActiveRecord::Base
  resourcify #rolify

  has_and_belongs_to_many :users
  has_many :restaurants

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_one :menu,dependent: :destroy
  has_many :daily_menus,dependent: :destroy

  belongs_to :organization
  validates :name,
            presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify #rolify gem
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  has_secure_password
  has_one :plan
  has_many :restaurants,:through => :organizations

  has_and_belongs_to_many :organizations

  validates :username,
            :presence => true,
            :uniqueness => true,
            :length => { maximum: 30 }

  validates :email,
            presence: true,
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }



end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for(object)
    #render error message(views/application html template),i prilagodjavanje lokalnih varijabli unutar 'application/error_message sa ulaznom
    render(:partial => 'application/error_messages', :locals => {:object => object})
  end

  def plan_name(plan_id)
    plan_name = Plan.where(:id => plan_id).pluck(:name).first
  end

  def active_link?(test_path)
    return 'active' if request.original_url == test_path
    ''
  end

  def set_visibility_text(obj)
    if obj.visibility
      "Visible"
    else
      "Hiden"
    end
  end

  def set_class_for_visibility(obj)
    if obj.visibility
      "btn btn-danger btn-md visibility"
    else
      "btn btn-primary btn-md visibility"
    end
  end



end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_menage_side_menu.html.erb
<div class="sidebar-nav">
  <div class="well" style="width:250px; padding: 8px 0;">
    <ul class="nav nav-list">
      <% if @restaurant %>
      <li class="nav-header text-center">Restoran: <%= @restaurant.name  %></li>
      <li class="<%= active_link?(new_restaurant_url) %>" >
        <%= link_to content_tag(:i,'Add New Restaurant',:class=>"icon-home"),new_restaurant_path,remote:true %>
      </li>
      <% if  @restaurant.menu.nil? %>
          <li  class="<%= active_link?(new_menu_url) %>">
            <%= link_to "Add Menu",new_menu_path(:restaurant_id => @restaurant.id),:class=>'add_menu_side',remote:true %>
          </li>
      <% else%>
          <li class="<%= active_link?(list_menu_url(@restaurant.id)) %>">
            <%= link_to "Menage Menu",list_menu_path(@restaurant.menu.id)%>
          </li>
      <% end %>
      <li class="<%= active_link?('#') %>">
        <%= link_to "All Daily Menus",menage_daily_menu_path(@restaurant.id) %>
      </li>
      <li class="<%= active_link?('#') %>">
         <%= link_to "Food Category Menage",category_path%>
       </li>
      <li class="<%= active_link?(new_daily_menu_url) %>">
        <%= link_to "Add Daily Menu",new_daily_menu_path(:restaurant_id => @restaurant.id),:class=>'add_new_daily_menu' %>
      </li><% end %>
      <li class="<%= active_link?('#') %>">
        <%= link_to "Orders",'#' %></li>
      <li><%= link_to content_tag(:i,'Logout',:class=>"icon-home"),access_path(current_user.id),:method => :delete %></li>
    </ul>
  </div>
</div>

app/views/shared/_menu_categories_left.html.erb
<%if @menu_category %>
  <div class="sidebar-nav" data-spy="affix" data-offset-top="50">
    <div class="well" style="width:200px; padding: 8px 0;">
      <ul class="nav nav-list">
        <% @menu_category.each do |cat| %>
            <li><%= link_to cat,"##{cat.downcase.split.join}",class:"scroll_link"%></li>
        <% end %>
      </ul>
    </div>
  </div>oliver

<% end %>

app/views/shared/_modal.html.erb
<div class="modal fade add_new_modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_daily_menu.html.erb
<div class="modal fade daily_menu" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <%= link_to "Add New Meal",'#',:class=>"btn btn-success newItem"%>
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">


      </div>
    </div>
  </div>
</div>

app/views/shared/_restaurant_menu_public.html.erb
    <div class="row">
        <div class="col-md-12">
         <%@categories.each do |category|%>
         <%if !category.items.empty?%>
            <div class="panel panel-success" id="<%=category.name.downcase.split.join%>" >
                <div class="panel-heading">
                   <h3 class="panel-title"><%= category.name%></h3>
                </div>
                <div class="panel-body">
                    <table class=" table table-responsive table-striped ">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Price</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                          <%@items.each do |item|%>
                             <%if item.category == category%>
                                <tr>
                                    <td>
                                        <h5><%=item.name%></br></h5>
                                        <small><%= truncate(item.description,length: 37)%></small>
                                    </td>
                                    <td><p><%=number_to_currency(item.price,:unit=>"€")%></p></td>
                                    <td>
                                        <%= form_tag cart_index_path,class:"form-inline",remote:true do %>
                                            <%= hidden_field_tag :item_id, item.id%>
                                            <%= number_field_tag :quantity,nil,value:1%>
                                            <p class="pull-right"><%= submit_tag "Add to card",class:"btn btn-success btn-sm"%></p>
                                        <%end%>
                                    </td>
                                </tr>
                             <%end%>
                          <%end%>
                        </tbody>
                     </table>
                </div>
             </div>
             <%end  %>
          <%end%>
        </div>
    </div>

app/views/shared/_shopping_card.html.erb
<div class="shopping_cart" data-spy="affix" data-offset-top="50">
  <div class="well" style="width:200px; padding: 8px 0;">
    <h5 class="text-center">Shopping Cart</h5>
    <%= render :partial => 'shared/shopping_cart_items'%>
    <%= link_to "Clen Cart",clean_cart_index_path,remote:true %>
  </div>
</div>

app/views/shared/_shopping_cart_items.html.erb
<% if cart_items && !cart_items.empty? %>
    <%cart_items.each do |item|%>
        <p><%= item.name %>
           <%= link_to cart_path(item.id),:method => :delete,class:"pull-right",remote:true do %>
                <span class="glyphicon glyphicon-trash"></span>
           <% end %><br>
            <%= item.quantity %> X <span class="pull-right"><%=number_to_currency((item.quantity * item.price),:unit=>"€")%></span>
        </p>
    <% end %>
   <h5>Total Price: <%=number_to_currency(cart_total,:unit=>'€')%></h5>
<% else %>
    <h4 class="text-center">Your Cart is Empty</h4>
<% end %>

app/views/shared/_side_menu.html.erb
<div class="sidebar-nav">
  <div class="well" style="width:250px; padding: 8px 0;">
    <ul class="nav nav-list">
      <li class="nav-header text-center"><%= current_user.organizations.first.name.capitalize %></li>
      <li><%= link_to content_tag(:i,'Add New Restaurant',:class=>"icon-home"),new_restaurant_path,remote:true %></li>
      <li><%= link_to content_tag(:i,'Restaurants',:class=>"icon-home"),restaurants_path %>
        <ul>
          <% @restaurants.each do |r|%>
          <li>
                <%= link_to r.name,menage_restaurant_path(r.slug)  %>
          </li>
          <% end %>
        </ul>
      </li>
      <li><%= link_to content_tag(:i,'Menus',:class=>"icon-home"),menus_path %></li>
      <li><%= link_to content_tag(:i,'Logout',:class=>"icon-home"),access_path(current_user.id),:method => :delete %></li>
    </ul>
  </div>
</div>