config/routes.rb
Rails.application.routes.draw do

  root :to=>'access#new'
  resources :users
  resources :categories
  resources :items
  resources :access,only: [ :new, :create, :destroy ]
  resources :setup_organization,only: [ :show,:update ]
  resources :admin,only: [:index]

  resources :cart,except: [:new,:show] do
    collection do
      get :clean
    end
  end


  resources :menus  do
    member do
      get :list
    end
  end

  resources :restaurants do
    member do
      get :menage
    end
  end

  resources :daily_menus do
    member do
      get :menage
      put :toggle_visibility
    end
  end

  get 'registration',:to=>'users#new'
  get 'home', :to => 'home#index'

end

app/models/Tenant.rb
class Tenant

  def initialize(user)
    @user = user
  end

  def restaurants
    owner? ?  Restaurant.where('organization_id = ?',@user.organizations.first.id).all : Restaurant.all.all
  end

  private



  def admin?
    @user.has_role? "admin"
  end

  def owner?
    @user.has_role? "owner" if @user
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new #not logged in user
      if user.has_role? :admin
        can :manage, :all
      elsif user.has_role? :owner
        can :manage,Restaurant,:organization_id => user.organizations.first.id
        can :manage,Menu
        can :manage,:admin
        can :read, :home

      else
        can :read, :home
      end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :items
   has_many :menus
  validates :name,
            :presence => true
end

app/models/daily_menu.rb
class DailyMenu < ActiveRecord::Base

  has_many :items,dependent: :destroy
  belongs_to :restaurant,:dependent => :destroy

  accepts_nested_attributes_for :items,
                                :allow_destroy => true,
                                :reject_if => :all_blank

  validates :title,
            :presence => true

  validates :restaurant_id,
            :presence=> true

  validates :price,
            :presence => true,
            :numericality => true
end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :menu
  belongs_to :daily_menu
  belongs_to :category

  validates :name,
            :presence => true
           # :length => {minimum: 2,maximum: 45}
 # validates :price,
           # :presence => true,
           # :numericality => true
  validates :category_id,
            :presence => true

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :restaurant
  has_many :categories,:through => :items
  has_many :items,:dependent => :destroy

  validates :title,
            :presence => true


end

app/models/organization.rb
class Organization < ActiveRecord::Base
  resourcify #rolify

  has_and_belongs_to_many :users
  has_many :restaurants

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_one :menu,dependent: :destroy
  has_many :daily_menus,dependent: :destroy

  belongs_to :organization
  validates :name,
            presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify #rolify gem
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  has_secure_password
  has_one :plan
  has_many :restaurants,:through => :organizations

  has_and_belongs_to_many :organizations

  validates :username,
            :presence => true,
            :uniqueness => true,
            :length => { maximum: 30 }

  validates :email,
            presence: true,
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }



end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  layout 'admin_menage_restaurant',:except => :show

  authorize_resource
  skip_authorize_resource :only => :show

  def index
    #if params[:id].present?
    #authorize! :show, @restaurant
      @restaurants = @tenant.restaurants
       #@restaurants =Restaurant.where(:organization_id =>current_user.organizations.find(params[:id]))
    #else
       #@restaurants = Restaurant.all
   # end
  end


  def new
    @restaurant = Restaurant.new
  end


  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.organization_id = current_user.organizations.first.id
    respond_to do |format|
      if @restaurant.save
        format.html {redirect_to @restaurant,notice: "Uspjesno ste kreirali restoran."}
        format.json {render action:'new',status: :created,location: @restaurant}
      else
        format.html{render action: 'new'}
        format.json{render json:@restaurant.errors,status: :unprocessable_entity}
      end
    end
  end

  def show
    @restaurant = Restaurant.friendly.find(params[:id])
    #check autorization cancan gem
   # authorize! :show, @restaurant
    @menus = Menu.where(:restaurant_id => @restaurant.id)

  end

  def edit
    @restaurant = Restaurant.friendly.find(params[:id])
  end

  def update
    @restaurant = Restaurant.friendly.find(params[:id])
      respond_to do |format|
        if @restaurant.update_attributes(restaurant_params)
          format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @restaurant.errors, status: :unprocessable_entity }
        end
      end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    respond_to do |format|
      format.html{ redirect_to restaurant_url }
      format.json{ head :no_content }
    end
  end


  def menage
    @restaurant = Restaurant.friendly.find(params[:id])
    @menu = Menu.new
    @daily_menu = DailyMenu.new
  end




  private
  def restaurant_params
    params.require(:restaurant).permit(:name,:description,:organization_id)
  end


end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for(object)
    #render error message(views/application html template),i prilagodjavanje lokalnih varijabli unutar 'application/error_message sa ulaznom
    render(:partial => 'application/error_messages', :locals => {:object => object})
  end

  def plan_name(plan_id)
    plan_name = Plan.where(:id => plan_id).pluck(:name).first
  end

  def active_link?(test_path)
    return 'active' if request.original_url == test_path
    ''
  end

  def set_visibility_text(obj)
    if obj.visibility
      "Visible"
    else
      "Hiden"
    end
  end

  def set_class_for_visibility(obj)
    if obj.visibility
      "btn btn-danger btn-md visibility"
    else
      "btn btn-primary btn-md visibility"
    end
  end



end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/daily_menus_helper.rb
module DailyMenusHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/restaurants/_form.html.erb
 <% if @restaurant.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@restaurant.errors.count, "error") %>
            prohibited this organization from being saved:</h2>
          <ul>
            <% @restaurant.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
 <% end %>
    <%= form_for(@restaurant) do |f|%>
        <div class="form-group">
          <%= f.label 'Restaurant Name' %>
          <%= f.text_field :name, :class=>"form-control", :placeholder=> "Restaurant Name" %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, :class=>"form-control",:rows=>"3", :placeholder => "Restaurant Description" %>
        </div>
        <div class="form-group">
            <%=f.submit "Create Restaurant",:class=>'btn btn-primary'%>
            <%= link_to "Cancel",'#',:class=>"btn btn-default",:data=>{:dismiss=>"modal"}%>
        </div>
     <%end%>

app/views/restaurants/edit.html.erb
<%= form_for(@restaurant) do |f| %>
    <%= render :partial => 'restaurants/form',:locals=>{f: f}%>
    <%= f.submit 'Edit Restaurant', :class=>"btn btn-default" %> <%= link_to 'Cancel',restaurants_path,:class=>"btn btn-default" %>
<% end %>

app/views/restaurants/index.html.erb
<% @restaurants.each do |r|%>
<%=link_to r.name,menage_restaurant_path(r.slug)  %>
<% end %>

app/views/restaurants/menage.html.erb
<h1><%= @restaurant.name%></h1>

app/views/restaurants/new.html.erb
<%= render :partial=>'restaurants/form'%>

app/views/restaurants/new.js.erb
var modal = $('.add_new_modal')
var title = $('.modal-title')

title.empty()
modal.find('.modal-body').empty();
title.html('Add New Restaurant').addClass('text-center')
modal.find('.modal-body').append("<%= j render :partial => 'restaurants/form'%>")
modal.modal('show')

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<% if !@restaurant.menu %>
    <button class="btn btn-success"><%= link_to "Dodaj Menu",new_menu_path(:restaurant_id =>@restaurant.id) %></button>
<% end %>
<h3>Menus</h3>
<% if @menus.size > 0 %>
    <%= @menus.each do |m|  %>
        <%= link_to m.title,menu_path(m) %>
    <% end %>
<% else %>
    <h3>Ovaj restoran neposjeduje kreiran menu</h3>
 <% end %>