config/routes.rb
Rails.application.routes.draw do

  root :to=>'access#new'
  resources :users
  resources :categories
  resources :items
  resources :access,only: [ :new, :create, :destroy ]
  resources :setup_organization,only: [ :show,:update ]
  resources :admin,only: [:index]

  resources :cart,except: [:new,:show] do
    collection do
      get :clean
    end
  end


  resources :menus  do
    member do
      get :list
    end
  end

  resources :restaurants do
    member do
      get :menage
    end
  end

  resources :daily_menus do
    member do
      get :menage
      put :toggle_visibility
    end
  end

  get 'registration',:to=>'users#new'
  get 'home', :to => 'home#index'

end

app/models/Tenant.rb
class Tenant

  def initialize(user)
    @user = user
  end

  def restaurants
    owner? ?  Restaurant.where('organization_id = ?',@user.organizations.first.id).all : Restaurant.all.all
  end

  private



  def admin?
    @user.has_role? "admin"
  end

  def owner?
    @user.has_role? "owner" if @user
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new #not logged in user
      if user.has_role? :admin
        can :manage, :all
      elsif user.has_role? :owner
        can :manage,Restaurant,:organization_id => user.organizations.first.id
        can :manage,Menu
        can :manage,:admin
        can :read, :home

      else
        can :read, :home
      end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :items
   has_many :menus
  validates :name,
            :presence => true
end

app/models/daily_menu.rb
class DailyMenu < ActiveRecord::Base

  has_many :items,dependent: :destroy
  belongs_to :restaurant,:dependent => :destroy

  accepts_nested_attributes_for :items,
                                :allow_destroy => true,
                                :reject_if => :all_blank

  validates :title,
            :presence => true

  validates :restaurant_id,
            :presence=> true

  validates :price,
            :presence => true,
            :numericality => true
end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :menu
  belongs_to :daily_menu
  belongs_to :category

  validates :name,
            :presence => true
           # :length => {minimum: 2,maximum: 45}
 # validates :price,
           # :presence => true,
           # :numericality => true
  validates :category_id,
            :presence => true

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :restaurant
  has_many :categories,:through => :items
  has_many :items,:dependent => :destroy

  validates :title,
            :presence => true


end

app/models/organization.rb
class Organization < ActiveRecord::Base
  resourcify #rolify

  has_and_belongs_to_many :users
  has_many :restaurants

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_one :menu,dependent: :destroy
  has_many :daily_menus,dependent: :destroy

  belongs_to :organization
  validates :name,
            presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify #rolify gem
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  has_secure_password
  has_one :plan
  has_many :restaurants,:through => :organizations

  has_and_belongs_to_many :organizations

  validates :username,
            :presence => true,
            :uniqueness => true,
            :length => { maximum: 30 }

  validates :email,
            presence: true,
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }



end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    respond_to  do |format|
      if @category.save
        @last_category = Category.last
        format.html{redirect_to categories_path,notice:"uspjesno kreiran"}
        format.js{}
      else
        format.html{render 'categories/new'}
      end
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @categories = Category.all
    respond_to do |format|
      if @category.update_attributes(category_params)
        format.html{redirect_to category_path,notice: 'Changed'}
        format.js{}
      else
        format.html{render 'edit',notice:"Something went wrong"}
      end
    end

  end

  def destroy
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.destroy
        format.html{redirect_to category_path,notice:"Successfully deleted" }
        format.js{}
      end
    end

  end


  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for(object)
    #render error message(views/application html template),i prilagodjavanje lokalnih varijabli unutar 'application/error_message sa ulaznom
    render(:partial => 'application/error_messages', :locals => {:object => object})
  end

  def plan_name(plan_id)
    plan_name = Plan.where(:id => plan_id).pluck(:name).first
  end

  def active_link?(test_path)
    return 'active' if request.original_url == test_path
    ''
  end

  def set_visibility_text(obj)
    if obj.visibility
      "Visible"
    else
      "Hiden"
    end
  end

  def set_class_for_visibility(obj)
    if obj.visibility
      "btn btn-danger btn-md visibility"
    else
      "btn btn-primary btn-md visibility"
    end
  end



end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/daily_menus_helper.rb
module DailyMenusHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category_table.html.erb
<div class="table-responsive category_table">
  <table id="mytable" class="table table-bordred table-striped">
    <thead>
    <th>#</th>
    <th>Category Name</th>
    <th>Created_at</th>
    <th>Edit</th>
    <th>Delete</th>
    </thead>
    <tbody>
    <% @categories.each do |category| %>
        <tr>
          <td><%= category.id %></td>
          <td><%= category.name %></td>
          <td><%= category.created_at%></td>
          <td>
            <%= link_to edit_category_path(category.id),:remote => true,:class=> "btn btn-primary btn-xs edit_category" do %>
                <%= content_tag(:span,"",:class=>"glyphicon glyphicon-pencil")%>
            <% end %>
          </td>
          <td>
            <%= link_to category_path(category.id),:remote => true, :id=>"delete_category",method: :delete,:class=> "btn btn-danger btn-xs"  do %>
                <%= content_tag(:span,"",:class=>"glyphicon glyphicon-trash")%>
            <% end %>
          </td>

        </tr>
    <%end%>
        </tbody>
    </table>
</div>

app/views/categories/_form.html.erb
     <%= error_messages_for(@category)%>
    <%= form_for @category,:html=>{ :class=>'form-inline' },:remote=>true do |f|%>
        <div class="form-group ">
          <%= f.label 'Category Name' %>
            <%= f.text_field :name,:class=>"form-control",  :placeholder=> "Category Name" %>
          </div>
          <%= f.submit "Edit Category",:class=>"btn btn-primary "%>
    <%end%>

app/views/categories/create.js.erb
$.ajax({
    success:function(){
        $('#mytable').append( "<tr>"+
                "<td><%= @last_category.id %></td>"+
                "<td><%= @last_category.name %></td>"+
                "<td><%= @last_category.created_at %></td>"+
                "<td><a href='/categories/<%= j  @last_category.id.to_s %>/edit' class ='btn btn-primary btn-xs edit_category' data-remote='true'><span class='glyphicon glyphicon-pencil'></span></a></td>"+
                "<td><a id = 'delete_category' href='/categories/<%= j  @last_category.id.to_s %>' data-remote='true' data-method='delete' class ='btn btn-danger btn-xs'data-remote='true'><span class='glyphicon glyphicon-trash'></span></a></td>"+
             "</tr>"
        )
        $('.form').hide();
        $('#add_category').show()
    }

})

app/views/categories/destroy.js.erb
$('#delete_category ').on('ajax:success',function(){
   $(this).closest('tr').fadeOut('slow',function(){
       $(this).remove()
   })

});

app/views/categories/edit.html.erb
<%=render 'categories/form' %>

app/views/categories/edit.js.erb
$('.edit_category').on('ajax:success',function(){
    $('.form').html("<%= j render 'categories/form' %>")
    $('#add_category').hide()
})

app/views/categories/index.html.erb
<div class="col-md-12">
  <h4>All Categories</h4>
    <%= link_to "Add Category",new_category_path,:remote => true,:class => 'btn btn-info',:id =>'add_category'%>
  <div class="col-lg-12 form"></div>
    <%= render 'categories/category_table' %>
</div>

app/views/categories/new.html.erb
<%= render 'categories/form'%>

app/views/categories/new.js.erb
$('#add_category').on('click',function(){
    $('.form').html("<%= j render 'categories/form'%>");
    $('#add_category').hide()
    $('.form').show();
})

app/views/categories/update.js.erb
$.ajax({
    success : function(){
        $('.form').empty()
        $('.category_table').html("<%= j render(:partial => 'categories/category_table')%>");
        $('#add_category').show()
    }
})